tools: add missing headers
../tools/list-compatible-styli.c:73:10: error: implicit declaration of function 'basename' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                       basename(argv[0]));
                       ^
../tools/list-compatible-styli.c:73:10: error: format specifies type 'char *' but the argument has type 'int' [-Werror,-Wformat]
                       basename(argv[0]));
                       ^~~~~~~~~~~~~~~~~
../tools/list-devices.c:58:10: error: implicit declaration of function 'basename' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                       basename(argv[0]));
                       ^
../tools/list-devices.c:58:10: error: format specifies type 'char *' but the argument has type 'int' [-Werror,-Wformat]
                       basename(argv[0]));
                       ^~~~~~~~~~~~~~~~~