meson: chase fcbf0bbfcffd to unbreak on non-Linux without evdev headers
ninja: Entering directory `_build'
[4/20] Compiling C object 'test-load@exe/test_test-load.c.o'.
FAILED: test-load@exe/test_test-load.c.o
cc -Itest-load@exe -I. -I.. -I../libwacom -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -g -Wno-unused-parameter -fvisibility=hidden -Wmissing-prototypes -Wstrict-prototypes '-DTOPSRCDIR="/tmp/libwacom"' -MD -MQ 'test-load@exe/test_test-load.c.o' -MF 'test-load@exe/test_test-load.c.o.d' -o 'test-load@exe/test_test-load.c.o' -c ../test/test-load.c
../test/test-load.c:31:10: fatal error: 'linux/input-event-codes.h' file not found
 #include <linux/input-event-codes.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[5/20] Compiling C object 'wacom@sha/libwacom_libwacom-database.c.o'.
FAILED: wacom@sha/libwacom_libwacom-database.c.o
cc -Iwacom@sha -I. -I.. -I../libwacom -I/usr/local/include/gudev-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -g -Wno-unused-parameter -fvisibility=hidden -Wmissing-prototypes -Wstrict-prototypes -fPIC '-DG_LOG_DOMAIN="libwacom"' '-DDATADIR="/usr/local/share/libwacom"' -MD -MQ 'wacom@sha/libwacom_libwacom-database.c.o' -MF 'wacom@sha/libwacom_libwacom-database.c.o.d' -o 'wacom@sha/libwacom_libwacom-database.c.o' -c ../libwacom/libwacom-database.c
../libwacom/libwacom-database.c:32:10: fatal error: 'linux/input-event-codes.h' file not found
 #include <linux/input-event-codes.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[6/20] Compiling C object 'wacom@sha/libwacom_libwacom.c.o'.
FAILED: wacom@sha/libwacom_libwacom.c.o
cc -Iwacom@sha -I. -I.. -I../libwacom -I/usr/local/include/gudev-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -g -Wno-unused-parameter -fvisibility=hidden -Wmissing-prototypes -Wstrict-prototypes -fPIC '-DG_LOG_DOMAIN="libwacom"' '-DDATADIR="/usr/local/share/libwacom"' -MD -MQ 'wacom@sha/libwacom_libwacom.c.o' -MF 'wacom@sha/libwacom_libwacom.c.o.d' -o 'wacom@sha/libwacom_libwacom.c.o' -c ../libwacom/libwacom.c
../libwacom/libwacom.c:39:10: fatal error: 'linux/input-event-codes.h' file not found
 #include <linux/input-event-codes.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.